Fix PWM not working in Raspi 4
stianeikeland/go-rpio pull request #70
Opened 2020-12-31 17:00 UTC by rami-dabain

Minor permission problems

2021-01-14 18:17 UTC, baumgarb commented
Nice work man, just tried it out and it fixes the issue. Sweet! :)

2021-03-22 17:02 UTC, rami-dabain commented
Looks like this library is not maintained anymore @stianeikeland  i can help maintain this if you give me write access to this repo :)

2021-04-11 02:56 UTC, sagikazarmark requested changes

2021-04-11 02:56 UTC, sagikazarmark commented on rpio.go
> +
If this PR is about fixing a specific issue, it shouldn't contain new features.

2021-08-12 07:22 UTC, Peelz commented
Is this PR will merged ?

2021-08-19 00:37 UTC, closed without merging

2021-08-19 00:39 UTC, drahoslove commented
@rami-dabain Fixed it myself in another commit because your master branch contained also an additional feature not relate to the issue, as mentioned in the review comment.